// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package schema

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GismeteoWeatherGatewayClient is the client API for GismeteoWeatherGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GismeteoWeatherGatewayClient interface {
	GetWeather(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Weather, error)
}

type gismeteoWeatherGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewGismeteoWeatherGatewayClient(cc grpc.ClientConnInterface) GismeteoWeatherGatewayClient {
	return &gismeteoWeatherGatewayClient{cc}
}

func (c *gismeteoWeatherGatewayClient) GetWeather(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Weather, error) {
	out := new(Weather)
	err := c.cc.Invoke(ctx, "/schema.GismeteoWeatherGateway/GetWeather", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GismeteoWeatherGatewayServer is the server API for GismeteoWeatherGateway service.
// All implementations must embed UnimplementedGismeteoWeatherGatewayServer
// for forward compatibility
type GismeteoWeatherGatewayServer interface {
	GetWeather(context.Context, *Empty) (*Weather, error)
	mustEmbedUnimplementedGismeteoWeatherGatewayServer()
}

// UnimplementedGismeteoWeatherGatewayServer must be embedded to have forward compatible implementations.
type UnimplementedGismeteoWeatherGatewayServer struct {
}

func (UnimplementedGismeteoWeatherGatewayServer) GetWeather(context.Context, *Empty) (*Weather, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeather not implemented")
}
func (UnimplementedGismeteoWeatherGatewayServer) mustEmbedUnimplementedGismeteoWeatherGatewayServer() {
}

// UnsafeGismeteoWeatherGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GismeteoWeatherGatewayServer will
// result in compilation errors.
type UnsafeGismeteoWeatherGatewayServer interface {
	mustEmbedUnimplementedGismeteoWeatherGatewayServer()
}

func RegisterGismeteoWeatherGatewayServer(s grpc.ServiceRegistrar, srv GismeteoWeatherGatewayServer) {
	s.RegisterService(&GismeteoWeatherGateway_ServiceDesc, srv)
}

func _GismeteoWeatherGateway_GetWeather_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GismeteoWeatherGatewayServer).GetWeather(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.GismeteoWeatherGateway/GetWeather",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GismeteoWeatherGatewayServer).GetWeather(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GismeteoWeatherGateway_ServiceDesc is the grpc.ServiceDesc for GismeteoWeatherGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GismeteoWeatherGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schema.GismeteoWeatherGateway",
	HandlerType: (*GismeteoWeatherGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWeather",
			Handler:    _GismeteoWeatherGateway_GetWeather_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema.proto",
}
